[theme]
base="light"

[server]
enableCORS = false

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false

[ui]
hideMenu = true
[browser]
gatherUsageStats = false

[server]
enableXsrfProtection = false

[ui]
hideTopBar = true


